const TeamBuildData = {
  mer: [
    {
      id: 1,
      name: "Lewis Hamilton",
      seasonPoints: 100,
      price: 9,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 2,
      name: "George Russell",
      seasonPoints: 100,
      price: 5,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  rbr: [
    {
      id: 3,
      name: "Max Verstappen",
      seasonPoints: 100,
      price: 12,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 4,
      name: "Sergio Perez",
      seasonPoints: 100,
      price: 6,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  fer: [
    {
      id: 5,
      name: "Charles Leclerc",
      seasonPoints: 100,
      price: 6.2,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 6,
      name: "Carlos Sainz",
      seasonPoints: 100,
      price: 5.4,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  mcl: [
    {
      id: 7,
      name: "Lando Norris",
      seasonPoints: 100,
      price: 5.9,
      overtakes: "5",
      bestRaceResult: "7th",
      bestQualifyingResult: "5th",
    },
    {
      id: 8,
      name: "Daniel Ricciardo",
      seasonPoints: 100,
      price: 4,
      overtakes: "77",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  amr: [
    {
      id: 9,
      name: "Sebastien Vettel",
      seasonPoints: 100,
      price: 6,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 10,
      name: "Lance Stroll",
      seasonPoints: 100,
      price: 3,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  alp: [
    {
      id: 11,
      name: "Fernando Alonso",
      seasonPoints: 100,
      price: 7,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 12,
      name: "Esteban Ocon",
      seasonPoints: 100,
      price: 5,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  atr: [
    {
      id: 13,
      name: "Yuki Tsunoda",
      seasonPoints: 100,
      price: 5,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 14,
      name: "Pierre Gasly",
      seasonPoints: 100,
      price: 6,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  ars: [
    {
      id: 15,
      name: "Valterri Bottas",
      seasonPoints: 100,
      price: 7,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 16,
      name: "Guanyu Zhou",
      seasonPoints: 100,
      price: 5,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  wil: [
    {
      id: 17,
      name: "Alexander Albon",
      seasonPoints: 100,
      price: 3,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 18,
      name: "Nicholas Latifi",
      seasonPoints: 100,
      price: 2,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  haa: [
    {
      id: 19,
      name: "Mick Schmuacher",
      seasonPoints: 100,
      price: 4,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 20,
      name: "Kevin Magnussen",
      seasonPoints: 100,
      price: 5,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
};

const TeamBuildDataDB = [
  [
    {
      name: "mer",
      drivers: [
        {
          id: 1,
          name: "Lewis Hamilton",
          seasonPoints: 100,
          price: 9,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
        {
          id: 2,
          name: "George Russell",
          seasonPoints: 100,
          price: 5,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
      ],
    },
  ],
  [
    {
      name: "rbr",
      drivers: [
        {
          id: 3,
          name: "Max Verstappen",
          seasonPoints: 100,
          price: 12,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
        {
          id: 4,
          name: "Sergio Perez",
          seasonPoints: 100,
          price: 6,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
      ],
    },
  ],
  [
    {
      name: "fer",
      drivers: [
        {
          id: 5,
          name: "Charles Leclerc",
          seasonPoints: 100,
          price: 6.2,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
        {
          id: 6,
          name: "Carlos Sainz",
          seasonPoints: 100,
          price: 5.4,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
      ],
    },
  ],
  [
    {
      name: "mcl",
      drivers: [
        {
          id: 7,
          name: "Lando Norris",
          seasonPoints: 100,
          price: 5.9,
          overtakes: "5",
          bestRaceResult: "7th",
          bestQualifyingResult: "5th",
        },
        {
          id: 8,
          name: "Daniel Ricciardo",
          seasonPoints: 100,
          price: 4,
          overtakes: "77",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
      ],
    },
  ],
  [
    {
      name: "amr",
      drivers: [
        {
          id: 9,
          name: "Sebastien Vettel",
          seasonPoints: 100,
          price: 6,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
        {
          id: 10,
          name: "Lance Stroll",
          seasonPoints: 100,
          price: 3,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
      ],
    },
  ],
  [
    {
      name: "alp",
      drivers: [
        {
          id: 11,
          name: "Fernando Alonso",
          seasonPoints: 100,
          price: 7,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
        {
          id: 12,
          name: "Esteban Ocon",
          seasonPoints: 100,
          price: 5,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
      ],
    },
  ],
  [
    {
      name: "atr",
      drivers: [
        {
          id: 13,
          name: "Yuki Tsunoda",
          seasonPoints: 100,
          price: 5,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
        {
          id: 14,
          name: "Pierre Gasly",
          seasonPoints: 100,
          price: 6,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
      ],
    },
  ],
  [
    {
      name: "ars",
      drivers: [
        {
          id: 15,
          name: "Valterri Bottas",
          seasonPoints: 100,
          price: 7,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
        {
          id: 16,
          name: "Guanyu Zhou",
          seasonPoints: 100,
          price: 5,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
      ],
    },
  ],
  [
    {
      name: "wil",
      drivers: [
        {
          id: 17,
          name: "Alexander Albon",
          seasonPoints: 100,
          price: 3,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
        {
          id: 18,
          name: "Nicholas Latifi",
          seasonPoints: 100,
          price: 2,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
      ],
    },
  ],
  [
    {
      name: "haa",
      drivers: [
        {
          id: 19,
          name: "Mick Schmuacher",
          seasonPoints: 100,
          price: 4,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
        {
          id: 20,
          name: "Kevin Magnussen",
          seasonPoints: 100,
          price: 5,
          overtakes: "5",
          bestRaceResult: "4th",
          bestQualifyingResult: "4th",
        },
      ],
    },
  ],
];

//const TeamBuildDataDB = [{}];

export { TeamBuildData, TeamBuildDataDB };
