export const TeamBuildData = {
  mer: [
    {
      id: 1,
      name: "Lewis Hamilton",
      price: 9,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 2,
      name: "George Russell",
      price: 5,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  rbr: [
    {
      id: 3,
      name: "Max Verstappen",
      price: 12,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 4,
      name: "Sergio Perez",
      price: 6,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  fer: [
    {
      id: 5,
      name: "Charles Leclerc",
      price: 6.2,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 6,
      name: "Carlos Sainz",
      price: 5.4,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  mcl: [
    {
      id: 7,
      name: "Lando Norris",
      price: 5.9,
      overtakes: "5",
      bestRaceResult: "7th",
      bestQualifyingResult: "5th",
    },
    {
      id: 8,
      name: "Daniel Ricciardo",
      price: 4,
      overtakes: "77",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  amr: [
    {
      id: 9,
      name: "Sebastien Vettel",
      price: 6,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 10,
      name: "Lance Stroll",
      price: 3,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  alp: [
    {
      id: 11,
      name: "Fernando Alonso",
      price: 7,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 12,
      name: "Esteban Ocon",
      price: 5,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  atr: [
    {
      id: 13,
      name: "Yuki Tsunoda",
      price: 5,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 14,
      name: "Pierre Gasly",
      price: 6,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  ars: [
    {
      id: 15,
      name: "Valterri Bottas",
      price: 7,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 16,
      name: "Guanyu Zhou",
      price: 5,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  wil: [
    {
      id: 17,
      name: "Alexander Albon",
      price: 3,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 18,
      name: "Nicholas Latifi",
      price: 2,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
  haa: [
    {
      id: 19,
      name: "Mick Schmuacher",
      price: 4,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
    {
      id: 20,
      name: "Kevin Magnussen",
      price: 5,
      overtakes: "5",
      bestRaceResult: "4th",
      bestQualifyingResult: "4th",
    },
  ],
};
