name: qualifying check
on:
  schedule:
    # Run every hour
    - cron: "0 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API ROUTE
        run: |
          curl --request GET \
          --url 'https://play.fantasygrid.app/api/admin/update-round/0-0-close-trading'
